/**
 * Build step: subset the Material Symbols Rounded variable font to just the icons
 * this app uses.
 *
 * The full variable font is ~5MB. Subsetting by ligature text does not help
 * (every icon name is ASCII, so glyph closure drags in nearly the whole font), so
 * instead we resolve each icon name to the private-use codepoint the font maps it
 * to (Material Symbols keeps the classic Material Icons codepoints, e.g. home =
 * U+E88A) and subset by those codepoints. The result is a few KB, keeps the
 * FILL / wght / GRAD / opsz axes, and works fully offline.
 *
 * Usage: node scripts/subset-icons.mjs
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import subsetFont from 'subset-font';

const require = createRequire(import.meta.url);
const fontkit = require('fontkit');

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const SRC_DIR = path.join(root, 'web', 'src');
const THEME_DIR = path.join(SRC_DIR, 'theme');
const ASSET_DIR = path.join(SRC_DIR, 'assets');
const FONT_SOURCE = path.join(root, 'node_modules', 'material-symbols', 'material-symbols-rounded.woff2');
const FONT_OUT = path.join(ASSET_DIR, 'material-symbols-rounded-subset.woff2');
const CSS_OUT = path.join(THEME_DIR, 'icon-font.css');
const MAP_OUT = path.join(THEME_DIR, 'icon-codepoints.ts');

/** Safety net: icons that may be referenced dynamically. */
const EXTRA_ICONS = [
  'check', 'check_circle', 'error', 'warning', 'info', 'visibility', 'visibility_off',
  'arrow_forward', 'arrow_back', 'chevron_left', 'chevron_right', 'expand_more', 'expand_less',
  'close', 'menu', 'more_vert', 'more_horiz', 'add', 'remove', 'delete', 'edit', 'save',
  'play_arrow', 'pause', 'stop', 'upload', 'download', 'share', 'refresh', 'sync', 'content_copy',
  'search', 'search_off', 'send', 'image', 'photo_camera', 'photo_library', 'mic', 'graphic_eq',
  'home', 'history', 'settings', 'label', 'lightbulb', 'account_tree', 'forum', 'help', 'schedule',
  'storage', 'palette', 'bolt', 'key', 'dark_mode', 'light_mode', 'summarize', 'article',
];

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else if (/\.(tsx?|jsx?|html)$/.test(entry.name)) files.push(full);
  }
  return files;
}

const files = await walk(SRC_DIR);
const names = new Set(EXTRA_ICONS);
for (const file of files) {
  const text = await readFile(file, 'utf8');
  // `icon="x"`, `name: 'x'` and ternaries such as `icon: a ? 'filter_list' : 'list'`
  for (const match of text.matchAll(/\b(?:name|icon)\b\s*[=:]\s*([^,;}\n]+)/g)) {
    for (const literal of match[1].matchAll(/['"]([a-z0-9_]+)['"]/g)) names.add(literal[1]);
  }
}

const icons = [...names].sort();

/* ------------------------------------------------- name -> PUA codepoint ---- */
const font = fontkit.openSync(FONT_SOURCE);
const byName = new Map();
for (const codepoint of font.characterSet) {
  if (codepoint < 0xe000 || codepoint > 0xf8ff) continue;
  const glyph = font.glyphForCodePoint(codepoint);
  if (glyph?.name && !byName.has(glyph.name)) byName.set(glyph.name, codepoint);
}

const codepoints = {};
const characters = [];
const missing = [];
for (const name of icons) {
  const codepoint = byName.get(name);
  if (!codepoint) {
    missing.push(name);
    continue;
  }
  codepoints[name] = codepoint;
  characters.push(String.fromCodePoint(codepoint));
}

if (missing.length) {
  console.warn(`! icons missing from the font (they will fall back to ligature text): ${missing.join(', ')}`);
}

/* ------------------------------------------------------------- write files -- */
await mkdir(ASSET_DIR, { recursive: true });
const source = await readFile(FONT_SOURCE);
const subset = await subsetFont(source, characters.join(''), { targetFormat: 'woff2' });
await writeFile(FONT_OUT, subset);

await writeFile(
  CSS_OUT,
  `/* AUTO-GENERATED by scripts/subset-icons.mjs - do not edit by hand.
   Material Symbols Rounded subset to the ${Object.keys(codepoints).length} icons used by the app. */
@font-face {
  font-family: 'Material Symbols Rounded';
  font-style: normal;
  font-weight: 100 700;
  font-display: block;
  src: url('../assets/material-symbols-rounded-subset.woff2') format('woff2');
}
`,
);

const entries = Object.entries(codepoints)
  .map(([name, codepoint]) => `  ${JSON.stringify(name)}: 0x${codepoint.toString(16)},`)
  .join('\n');

await writeFile(
  MAP_OUT,
  `/* AUTO-GENERATED by scripts/subset-icons.mjs - do not edit by hand.
   Private use codepoints of the Material Symbols Rounded glyphs shipped in the subset font. */
export const ICON_CODEPOINTS: Record<string, number> = {
${entries}
};

/** The glyph character for an icon name ('' when the icon is not in the subset). */
export function iconChar(name: string): string {
  const codepoint = ICON_CODEPOINTS[name];
  return codepoint ? String.fromCodePoint(codepoint) : '';
}
`,
);

let subsetAxes = [];
try {
  subsetAxes = Object.keys(fontkit.openSync(FONT_OUT).variationAxes ?? {});
} catch {
  subsetAxes = [];
}

const kb = (buffer) => `${(buffer.length / 1024).toFixed(1)} KB`;
console.log(`icons : ${Object.keys(codepoints).length} mapped${missing.length ? `, ${missing.length} missing` : ''}`);
console.log(`font  : ${kb(source)} -> ${kb(subset)} (variable axes: ${subsetAxes.join(', ') || 'none'})`);
console.log(`files : ${path.relative(root, CSS_OUT)}, ${path.relative(root, MAP_OUT)}`);
