package com.app.m3expressive

/* AUTO-GENERATED by scripts/import-schedule.mjs - do not edit by hand.
   Source: 学生课表.doc (广东财贸信创3班版权所有 · 2026-2027-1 · 7 节次 × 7 天) */

/** 一门课程（已从教务系统导出的课表中解析）。 */
data class ScheduleCourse(
    val name: String,
    /** 周次范围，例如 "4;6-9;12-20"；为空表示每周 */
    val weeks: String,
    val teacher: String,
    val room: String,
)

/** 某个节次在四天/一周里的安排。 */
data class SchedulePeriod(
    val period: String,
    val time: String,
    /** morning / noon / afternoon / evening */
    val section: String,
    /** 周一优先，每天可能有 0..n 门课 */
    val days: List<List<ScheduleCourse>>,
)

/** 内嵌课表：App 自带，无需手动导入。 */
object EmbeddedSchedule {
    const val OWNER = "广东财贸信创3班版权所有"
    const val TERM = "2026-2027-1"
    const val TERM_START = "2026-08-31"

    val days = listOf("星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日")

    val periods = listOf(
        SchedulePeriod(
            "第1-2节",
            "08:30-09:55",
            "morning",
            listOf(
                listOf(),
                listOf(),
                listOf(),
                listOf(ScheduleCourse("智慧财经素养", "4;6-9;12-20", "韩曌", "16-203")),
                listOf(ScheduleCourse("习近平新时代中国特色社会主义思想概论", "13-20", "肖扬", "25-207")),
                listOf(),
                listOf()
            ),
        ),
        SchedulePeriod(
            "第3-4节",
            "10:15-11:40",
            "morning",
            listOf(
                listOf(),
                listOf(ScheduleCourse("人工智能通识课", "4;7-9;12-21", "赖燕璇", "3-402")),
                listOf(ScheduleCourse("劳动教育（一）", "12-14", "李强", ""), ScheduleCourse("劳动教育（一）", "9-9", "李强", "2-201")),
                listOf(ScheduleCourse("习近平新时代中国特色社会主义思想概论", "4;6-9;12-20", "肖扬", "26-207")),
                listOf(),
                listOf(),
                listOf(ScheduleCourse("人工智能通识课", "3-3", "赖燕璇", "3-402"))
            ),
        ),
        SchedulePeriod(
            "第中午1-中午2节",
            "12:10-13:35",
            "noon",
            listOf(
                listOf(),
                listOf(),
                listOf(),
                listOf(),
                listOf(),
                listOf(),
                listOf()
            ),
        ),
        SchedulePeriod(
            "第5-6节",
            "14:10-15:35",
            "afternoon",
            listOf(
                listOf(ScheduleCourse("形势与政策（一）", "15-18", "朱涛", "2-206")),
                listOf(ScheduleCourse("国产化设备基础", "4;7-9;12-21", "林涌东", "1-401")),
                listOf(),
                listOf(),
                listOf(ScheduleCourse("国产操作系统管理", "3;6-9;12-20", "刘桂颜", "3-603")),
                listOf(),
                listOf(ScheduleCourse("国产化设备基础", "3-3", "林涌东", "1-401"))
            ),
        ),
        SchedulePeriod(
            "第7-8节",
            "15:55-17:20",
            "afternoon",
            listOf(
                listOf(ScheduleCourse("大学英语（一）", "4;7-9;12-21", "沈杰", "27-305")),
                listOf(ScheduleCourse("信息技术应用创新导论", "4;7-9;12-21", "李岚军", "3-402")),
                listOf(),
                listOf(ScheduleCourse("体育与健康（一）", "3-4;6-9;12-20", "陈正书", "清远校区西体育馆内羽毛球室")),
                listOf(ScheduleCourse("国产操作系统管理", "3;6-9;12-20", "刘桂颜", "3-603")),
                listOf(),
                listOf(ScheduleCourse("信息技术应用创新导论", "3-3", "李岚军", "3-402"))
            ),
        ),
        SchedulePeriod(
            "第9-10节",
            "18:10-19:35",
            "evening",
            listOf(
                listOf(),
                listOf(ScheduleCourse("大学生心理健康教育（一）", "4;8;12;14;16;18;20", "姚佩琪", "25-307")),
                listOf(ScheduleCourse("大学生职业生涯规划", "4;8;12;14;16;18;20", "黄健星", "16-202")),
                listOf(ScheduleCourse("创新创业教育（一）", "14-14", "张佳乐", "26-301")),
                listOf(),
                listOf(ScheduleCourse("大学生职业生涯规划", "6-6", "黄健星", "16-202")),
                listOf(ScheduleCourse("大学生心理健康教育（一）", "3-3", "姚佩琪", "25-307"))
            ),
        ),
        SchedulePeriod(
            "第11-12节",
            "19:55-21:20",
            "evening",
            listOf(
                listOf(),
                listOf(ScheduleCourse("创新创业教育（一）", "4;8;12;14;16;18", "张佳乐", "26-301")),
                listOf(ScheduleCourse("军事理论", "7;9;13;15;17;19;21", "陈璐", "25-403")),
                listOf(),
                listOf(),
                listOf(),
                listOf(ScheduleCourse("创新创业教育（一）", "3-3", "张佳乐", "26-301"))
            ),
        )
    )
}
