package com.app.m3expressive

/* AUTO-GENERATED by scripts/import-textbooks.mjs - do not edit by hand.
   Source: web/src/data/textbooks.json（由 12 张教材封面照片整理）*/

/** 一门课程的教材。 */
data class Textbook(
    val course: String,
    val title: String,
    val publisher: String,
    val edition: String? = null,
    val series: String? = null,
    /** 课程归属为推断匹配，界面上会标注“参考” */
    val reference: Boolean = false,
)

/** 内置教材库：课程名 → 教材。 */
object TextbookLibrary {
    val all = listOf(
    Textbook(
        course = "习近平新时代中国特色社会主义思想概论",
        title = "习近平新时代中国特色社会主义思想概论",
        publisher = "高等教育出版社 · 人民出版社",
        series = "马克思主义理论研究和建设工程重点教材",
    ),
    Textbook(
        course = "智慧财经素养",
        title = "智慧财经素养",
        publisher = "东北财经大学出版社",
        series = "广东省“十四五”职业教育规划教材",
    ),
    Textbook(
        course = "劳动教育（一）",
        title = "新时代大学生劳动教育",
        publisher = "上海交通大学出版社",
        edition = "第 2 版",
    ),
    Textbook(
        course = "军事理论",
        title = "军事理论与技能训练教程",
        publisher = "国防科技大学出版社",
        edition = "最新修订",
    ),
    Textbook(
        course = "形势与政策（一）",
        title = "时事报告大学生版",
        publisher = "时事报告杂志社",
        edition = "2026—2027 学年度 上",
    ),
    Textbook(
        course = "体育与健康（一）",
        title = "体育与健康",
        publisher = "高等教育出版社",
        series = "新形态一体化教材",
    ),
    Textbook(
        course = "大学生职业生涯规划",
        title = "大学生职业生涯规划",
        publisher = "东北师范大学出版社",
    ),
    Textbook(
        course = "大学英语（一）",
        title = "职通英语 Network Now 综合教程 1",
        publisher = "东北师范大学出版社",
        edition = "第四版",
    ),
    Textbook(
        course = "人工智能通识课",
        title = "AIGC 应用：人工智能交互式通识教程",
        publisher = "清华大学出版社",
    ),
    Textbook(
        course = "大学生心理健康教育（一）",
        title = "新时代大学生心理健康与积极教育",
        publisher = "武汉大学出版社",
        edition = "第二版",
    ),
    Textbook(
        course = "创新创业教育（一）",
        title = "大学生创新与创业教程——理论·案例·实训",
        publisher = "教育科学出版社",
        edition = "第三版",
    ),
    Textbook(
        course = "国产化设备基础",
        title = "IT 终端设备的配置与维护",
        publisher = "西安电子科技大学出版社",
        edition = "微课版",
        reference = true,
    )
    )

    private val byCourse = all.associateBy { it.course }

    /** 课程名 → 教材（先精确匹配，再按去掉括号后的名字匹配）。 */
    fun forCourse(courseName: String): Textbook? =
        byCourse[courseName] ?: byCourse.entries.firstOrNull { (course, _) ->
            normalize(course) == normalize(courseName) ||
                normalize(course).startsWith(normalize(courseName)) ||
                normalize(courseName).startsWith(normalize(course))
        }?.value

    private fun normalize(name: String): String =
        name.replace(Regex("[（(][^）)]*[）)]"), "").replace(Regex("[\\s·・、,，.。:：-]"), "").lowercase()
}
